kind: ServiceAccount
apiVersion: v1
metadata:
  name: registry-secret-manager

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-manager-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create","delete","get","list","watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-manager
roleRef:
  kind: ClusterRole 
  name: secret-manager-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: registry-secret-manager
  namespace: default

---
kind: Job
apiVersion: batch/v1
metadata:
  name: create-certs
spec:
  template:
    metadata:
      name: create-certs
    spec:
      restartPolicy: OnFailure
      serviceAccountName: registry-secret-manager
      containers:
        - name: create-certs
          image: amouat/create-certs-auto
          imagePullPolicy: Always
